### ISSUE TITLE
Compatibility with RxJS 6.3+

### ISSUE THREAD

**Issue by kirillgroshkov** [zyra/ionic-super-tabs#332]
After updating RxJS to 6.3 I start to see error `Observable.fromEvent is not a function`. Are there plans to support RxJS 6?

ps: actually, it worked with RxJS 6.2.2, but stopped after 6.3.

**Comment by ihadeed** [comment]
RxJS 6 will be supported once we update the project to Angular 6, and we'll do that as soon as Ionic 4 is stable.

**Comment by kirillgroshkov** [comment]
Ok. Clear enough.

Just a small afterthought. Different tools together form an ecosystem that depend on each other. Ionic actively promotes trying alpha, beta, rc releases before the final stable release. The more users try it and verify that it's working - the faster Ionic can stabilize their release. So, the faster incompatibilities are discovered and fixed - the faster whole ecosystem can bump and upgrade. By waiting for one tool to update it can create a "chicken&egg" situation. Of course, Ionic is the major player here (compared to ionic2-super-tabs), but still.

But what if someone will create a branch and PR of `ionic2-super-tabs` that works with Ionic4, will such PR be appreciated?

**Comment by ihadeed** [comment]
@kirillgroshkov You have a very good point.

We should start upgrading this project to work with Ionic 4, or at least explore the options we have (Angular vs Stencil, stay based on Ionic tabs or detach from it... etc).

**Comment by kirillgroshkov** [comment]
Great!

I'm actively tracking Ionic's progress and public statements. They say the *default* is Ionic-Angular (despite that internally Ionic4 is built with Stencil).

**Comment by lander854** [comment]
To temporarily fix it, change the following on 
node_modules\ionic2-super-tabs\dist\components\supertabs.js

Replacing the observable and fromevent imports 
to:
import { Observable, fromEvent } from 'rxjs';

And, replacing:
     var obsToMerge = [
            Observable.fromEvent(window, 'orientationchange'),
            Observable.fromEvent(window, 'resize')
        ];
to:
        var obsToMerge = [
            fromEvent(window, 'orientationchange'),
            fromEvent(window, 'resize')
        ];
